//---------------------------------------------------------------------------
//           KAMRAN-MD - YOUTUBE AUDIO DOWNLOADER (AUTO-DL)
//---------------------------------------------------------------------------

import { fileURLToPath } from 'url';
import yts from 'yt-search';
import axios from 'axios';
import { cmd } from '../command.js';

const __filename = fileURLToPath(import.meta.url);

/**
 * Normalizes YouTube URLs to a standard format
 */
function normalizeYouTubeUrl(url) {
  const match = url.match(/(?:youtu\.be\/|youtube\.com\/shorts\/|youtube\.com\/.*[?&]v=)([a-zA-Z0-9_-]{11})/);
  return match ? `https://youtube.com/watch?v=${match[1]}` : null;
}

/**
 * Fetch Audio Download Link using Vajira API (ytmp3)
 */
async function fetchAudioData(url, retries = 2) {
  try {
    // Vajira API endpoint for YouTube Audio (ytmp3)
    const apiUrl = `https://vajiraofc-apis.vercel.app/api/ytmp3?apikey=VajiraOfc&url=${encodeURIComponent(url)}&quality=128`;
    const response = await axios.get(apiUrl, { timeout: 25000 });
    const data = response.data;

    if (data && (data.status === true || data.status === 200) && (data.result || data.data)) {
      const res = data.result || data.data;
      return {
        audio_url: res.download || res.dl || res.mp3 || res.url,
        title: res.title || "YouTube Audio",
        thumbnail: res.thumbnail || res.image
      };
    }
    
    throw new Error("Vajira API failed to return audio link.");
  } catch (error) {
    if (retries > 0) {
      await new Promise((resolve) => setTimeout(resolve, 2000));
      return fetchAudioData(url, retries - 1);
    }
    console.error("Fetch Audio DL Error:", error.message);
    return null;
  }
}

// --- MAIN COMMAND: SONG / AUDIO ---

cmd(
  {
    pattern: "song80",
    alias: ["ytmp334", "audio8", "play8"],
    react: "🎵",
    desc: "Search and download audio from YouTube.",
    category: "download",
    filename: __filename,
  },
  async (conn, mek, m, { from, q, reply, prefix, command }) => {
    try {
      if (!q) return reply(`🎵 *Audio Downloader*\n\nUsage: \`${prefix + command} <song name or link>\`\nExample: \`${prefix + command} faded alan walker\``);

      await conn.sendMessage(from, { react: { text: "🔍", key: mek.key } });

      // Step 1: Search for the audio/video
      let ytdata;
      const cleanUrl = normalizeYouTubeUrl(q);

      if (cleanUrl) {
        const videoIdMatch = cleanUrl.match(/v=([a-zA-Z0-9_-]{11})/);
        if (videoIdMatch) {
          const searchResults = await yts({ videoId: videoIdMatch[1] });
          ytdata = searchResults;
        }
      } 
      
      if (!ytdata || !ytdata.url) {
        const searchResults = await yts(q);
        if (!searchResults || !searchResults.videos || searchResults.videos.length === 0) {
          return reply("❌ No audio found for your query!");
        }
        ytdata = searchResults.videos[0];
      }

      if (!ytdata || !ytdata.url) {
        return reply("❌ Could not retrieve audio details. Try searching with a direct link or different keywords.");
      }

      // Step 2: Send info message
      const infoText = `
🎵 *YT AUDIO DOWNLOADER* 🎵

📌 *Title:* ${ytdata.title || "N/A"}
🎬 *Channel:* ${ytdata.author?.name || 'Unknown'}
⏱️ *Duration:* ${ytdata.timestamp || 'N/A'}
👁️ *Views:* ${ytdata.views ? ytdata.views.toLocaleString() : 'N/A'}

_📥 Downloading your audio file, please wait..._

> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ DR KAMRAN`;

      await conn.sendMessage(from, { image: { url: ytdata.thumbnail || ytdata.image }, caption: infoText }, { quoted: mek });
      await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

      // Step 3: Fetch audio download link from Vajira API
      const dlData = await fetchAudioData(ytdata.url);

      if (!dlData || !dlData.audio_url) {
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        return reply("❌ Audio link could not be generated by the API. Please try again later.");
      }

      // Step 4: Send the Audio file (as document/audio format)
      await conn.sendMessage(
        from,
        {
          audio: { url: dlData.audio_url },
          mimetype: "audio/mpeg",
          ptt: false, // true karne par voice note ban jayega, false se normal audio song jayega
          caption: `✅ *${dlData.title}*\n\n*🚀 Powered by DR KAMRAN*`,
          contextInfo: {
            externalAdReply: {
              title: "YT AUDIO DOWNLOADER",
              body: dlData.title,
              thumbnailUrl: ytdata.thumbnail || ytdata.image,
              sourceUrl: ytdata.url,
              mediaType: 2,
              renderLargerThumbnail: true
            }
          }
        },
        { quoted: mek }
      );

      await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (e) {
      console.error("Audio DL Error:", e);
      await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
      reply(`⚠️ *Error:* ${e.message || "Something went wrong."}`);
    }
  }
);
